common/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views


app_name = "common"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'common/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name = 'common/logout.html'), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('common/', include('common.urls')),
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
]

post/urls.py
from django.urls import path
from .views import PostList, PostDelete, PostDetail, PostUpdate, PostCreate, PostLike, PostFavorite, PostLikeList,\
    PostFavoriteList, PostMyList
from django.conf.urls.static import static
from django.conf import settings

app_name = "post"
urlpatterns = [
    path("create/", PostCreate.as_view(), name='create'),
    path("like/<int:post_id>/", PostLike.as_view(), name='like'),
    path('favorite/<int:post_id>/', PostFavorite.as_view(), name='favorite'),
    path("delete/<int:pk>", PostDelete.as_view(), name='delete'),
    path("update/<int:pk>", PostUpdate.as_view(), name='update'),
    path("detail/<int:pk>", PostDetail.as_view(), name='detail'),
    path("like/", PostLikeList.as_view(), name='like_list'),
    path("favorite/", PostFavoriteList.as_view(), name='favorite_list'),
    path("mylist/", PostMyList.as_view(), name='mylist'),
    path("", PostList.as_view(), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models

# Create your models here.

post/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to= 'timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)

    def __str__(self):
        return "text : "+ self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

common/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ('username', 'email')

common/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import authenticate, login


def signup(request): #회원가입 화면 처리 함수
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1)
            login(request, user) # 로그인 인증되어 세션권한을 획득
            return redirect('index')
    else: #GET 방식일때
        form = UserForm()
    context = {'form': form}
    return render(request, 'common/signup.html', context)

post/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import Post
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse


class PostMyList(ListView):
    model = Post
    template_name = 'post/post_mylist.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       #로그인확인
            messages.warning(request, '로그인이 필요한기능입니다.')
            return HttpResponseRedirect('/')
        return super(PostMyList, self).dispatch(request, *args, **kwargs)



class PostLikeList(ListView):
    model = Post
    template_name = 'post/post_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       #로그인확인
            messages.warning(request, '로그인이 필요한기능입니다.')
            return HttpResponseRedirect('/')
        return super(PostLikeList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 좋아요한글 보여주기
        user = self.request.user
        queryset = user.like_post.all()
        return queryset


class PostFavoriteList(ListView):
    model = Post
    template_name = 'post/post_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       #로그인확인
            messages.warning(request, '로그인이 필요한기능입니다.')
            return HttpResponseRedirect('/')
        return super(PostFavoriteList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        # 저장한글 보여주기
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset


class PostLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       # 로그인확인
            return HttpResponseForbidden()
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk=post_id)
                user = request.user
                if user in post.like.all():
                    post.like.remove(user)
                else:
                    post.like.add(user)

            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)


class PostFavorite(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:       # 로그인확인
            return HttpResponseForbidden()
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk=post_id)
                user = request.user
                if user in post.favorite.all():
                    post.favorite.remove(user)
                else:
                    post.favorite.add(user)
            return HttpResponseRedirect('/')


class PostList(ListView):
    model = Post
    template_name_suffix = '_list'


class PostCreate(CreateView):
    model = Post
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 정상작동 한다면
            # form : 모델폼
            form.instance.save()
            return redirect('/')
        else:
            # 정상작동 X
            return self.render_to_response({'form': form})


class PostUpdate(UpdateView):
    model = Post
    fields = ['text', 'image']
    template_name_suffix = '_update'
    #success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정 권한이 없습니다.')
            return HttpResponseRedirect('/')
            # 삭제 페이지에서 권한이 없다 출력
            # detail페이지로 되돌아가서 삭제실패 출력
        else:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)


class PostDelete(DeleteView):
    model = Post
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정 권한이 없습니다.')
            return HttpResponseRedirect('/')
            # 삭제 페이지에서 권한이 없다 출력
            # detail페이지로 되돌아가서 삭제실패 출력
        else:
            return super(PostDelete, self).dispatch(request, *args, **kwargs)


class PostDetail(DetailView):
    model = Post
    template_name_suffix = '_detail'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
    .btn-like{
        display: inline-block;
        width: 25px;
        height: 25px;
        background:url({% static 'images/insta_icon.png' %});
        background-position: -155px -472px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }
    .btn-like.active{
    display: inline-block;
        width: 25px;
        height: 25px;
        background:url({% static 'images/insta_icon.png' %});
        background-position: -130px -472px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }
     .btn-favorite{
        display: inline-block;
        width: 25px;
        height: 25px;
        background:url({% static 'images/insta_icon.png' %});
        background-position: -155px -498px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }
    .btn-favorite.active{
    display: inline-block;z
        width: 25px;
        height: 25px;
        background:url({% static 'images/insta_icon.png' %});
        background-position: -130px -498px;
        text-indent: -9999px;
        overflow:hidden;
        border:none;
    }

    </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
                    aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                  <a class="navbar-brand" href="{% url 'post:index' %}">Team_Stargram</a>
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      {% if user.is_authenticated %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'post:create' %}">사진 추가</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'common:logout' %}">Logout</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'post:like_list' %}">좋아요한 사진보기</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'post:favorite_list' %}">저장한 사진보기</a>
                      </li>
                      {% else %}
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'common:login' %}">Login</a>
                      </li>
                      <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{% url 'common:signup' %}">회원가입</a>
                      </li>
                      {% endif %}
                  </ul>
                  <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
            </div>
      </div>
</nav>
<div class="container">
    {% if messages %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            {% for message in messages %}
            <div class="alert alert-{{message.tag}}">{{message}}</div>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
</div>
    {% endif %}

{% block content %}
{% endblock %}


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'post/css/bootstrap.css' %}">
<!--  static 하위의 파일을 불러올 때의 경로명 설정을 잘봐라.-->
    <title>로그인 : Team_stagram</title>
</head>

<body>
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4" >
            <a href="{% url 'post:index' %}">
                <img src="{% static 'post/images/home_black_24dp.png' %}"
                     alt="홈버튼"></a>
        </div>

        <div class="col-8 text-right">
            <span>아직 회원이 아니세요?&nbsp;&nbsp; <a href="{% url 'common:signup' %}">
                <button type="button" class="btn btn-secondary">가입하기</button></a></span>
        </div>
    </div>

    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
        {% include 'form_errors.html' %}
        <div class="form-group">
            <label for="username">아이디</label>
            <input type="text" class="form-control" name="username" id="username"
                 value="{{ form.username.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                 value="{{ form.password.value|default_if_none:''}}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>

    <!--        <form action="" method="post">-->
    <!--            {% csrf_token %}-->
    <!--            {{form.as_p}}-->
    <!--            <input type="submit" value="login" class = 'btn btn-outline-primary'>-->
    <!--        </form>-->

</div>
<script src="{% static 'post/js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'post/js/bootstrap.js' %}"></script>
</body>
</html>

templates/common/logout.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            로그아웃이 잘 되었습니다. </div>
        <a href="{% url 'accounts:login'%}" class="btn btn-outline-success">login 하기</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

templates/common/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'post/css/bootstrap.css' %}">
<!--  static 하위의 파일을 불러올 때의 경로명 설정을 잘봐라.-->
    <title>회원가입 : Team_stagram</title>
</head>

<body>
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <a href="{% url 'post:index' %}">
                <img src="{% static 'post/images/home_black_24dp.png' %}"
                     alt="홈버튼"></a>
        </div>
        <div class="col-8 text-right">
            <span>이미 회원이세요?&nbsp;&nbsp; <a href="{% url 'common:login' %}">
                <button type="button" class="btn btn-secondary">로그인</button></a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자이름</label>
            <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                    value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                    value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                    value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">등 록</button>
    </form>
</div>
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/post/post_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            모든 부분을 다 채워넣어주세요!!
        </div>
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

templates/post/post_delete.html
{% extends 'base.html' %}
{% block content %}
<!--진짜 지울건지 확인을 받아야 한다. form을 또 보여줄 필요가 없다.-->
<div class="alert alert-primary" role="alert">
  정말로 {{object}}를 삭제 하시겠습니까?
</div>
<form action="" method ="post">
    {% csrf_token%}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

templates/post/post_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="">
            <img src=" {{ object.image.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ object.author }}</h5>

                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'post:like' object.id %}"
                               class="float-left btn-like {% if user in object.like.all %} active {% endif %}">좋아요</a>
                        {% if object.like.all.count %}
                        <span class="float-left">
                                {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'post:favorite' object.id %}"
                               class="float-right btn-favorite {% if user in object.favorite.all %} active {% endif %}">저장하기</a>
                    </li>
                    <p class="card-text"> {{ object.text }} </p>
                    <li class="list-group-item">생성일 : {{object.created}}</li>
                </ul>
            </div>
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
            </div>
        </div>
    </div>

    <div class="col"></div>
</div>
{% endblock %}

templates/post/post_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col"></div>
        <div class="col-5">

            {% for object in object_list %}

            <article class="card mb-4">
                <div class="card-header">
                    {{ object.author }}
                </div>
                <img src="{{ object.image.url }}" class="card-img-top" alt="...">
                <div class="card-text">
                    <ul class="list-group list-group-flush">

                        <li class="list-group-item">
                            <a href="{% url 'post:like' object.id %}"
                               class="float-left btn-like {% if user in object.like.all %} active {% endif %}">좋아요</a>
                            {% if object.like.all.count %}
                            <span class="float-left">
                                {{object.like.all.count}}
                            </span>
                            {% endif %}
                            <a href="{% url 'post:favorite' object.id %}"
                               class="float-right btn-favorite {% if user in object.favorite.all %} active {% endif %}">저장하기</a>
                        </li>

                        <p class="card-text"> {{ object.text }} </p>
                    </ul>
                        <li class="list-group-item">생성일 : {{object.created}}</li>

                </div>
                <div class="card-body">
                    <a href="{% url 'post:detail' object.id %} " class="card-link">댓글달기</a>
                    {% if user == object.author %}
                    <a href="{% url 'post:update' object.id %} " class="card-link">수정하기</a>
                    <a href="{% url 'post:delete' object.id %} " class="card-link">삭제하기</a>
                    {% endif %}
                </div>
            </article>
            {% endfor %}
        </div>

        <div class="col">
            {% load static %}
            <div class="card" style="">
               <img src="{% static 'images/' %}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{user}}</h5>
                    <p class="card-text">회원님의 스토리를 확인하세요</p>
                    <a href="{% url 'post:mylist' %}" class="btn btn-primary">회원님의 스토리 이동</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/post/post_mylist.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<!-- Gallery -->
<div class="row">
  <div class="col-md-12">
      <div class="row">
          {% for object in object_list %}
          {% if object.author == request.user %}
          <figure class="col-md-4">
              <img src="{{object.image.url}}" class="w-100 shadow-1-strong rounded mb-4" alt="">
          </figure>
          {% endif %}
          {% endfor %}
      </div>
  </div>

</div>
<!-- Gallery -->

{% endblock %}

templates/post/post_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}